// Verifies the Dart port produces byte-identical output to the JS engine in
// decant.html, for the same seeds. The fixture (fixtures/engine_fixture.json)
// was generated by running the *exact* JS source (lines 358-551 of
// decant.html, byte-for-byte, extracted verbatim) in a real browser — see
// Phase 1 of flutter_port_plan.md: "every tuned balance number is invalid"
// if this ever diverges.
import 'dart:convert';
import 'dart:io';

import 'package:vialo/game/game.dart';
import 'package:test/test.dart';

late Map<String, dynamic> fixture;

List<List<int>> _tubes(dynamic raw) =>
    (raw as List).map((t) => (t as List).cast<int>()).toList();

void main() {
  setUpAll(() {
    final raw = File('test/game/fixtures/engine_fixture.json').readAsStringSync();
    fixture = jsonDecode(raw) as Map<String, dynamic>;
  });

  group('mb32 (mulberry32 RNG)', () {
    test('matches the JS sequence for a range of seeds', () {
      final seeds = (fixture['mb32'] as Map<String, dynamic>).keys;
      for (final seedStr in seeds) {
        final seed = int.parse(seedStr);
        final expected = (fixture['mb32'][seedStr] as List).cast<double>();
        final rnd = mb32(seed);
        final actual = List.generate(expected.length, (_) => rnd());
        for (var i = 0; i < expected.length; i++) {
          expect(
            actual[i],
            closeTo(expected[i], 1e-12),
            reason: 'mb32(seed=$seed) draw #$i',
          );
        }
      }
    });
  });

  group('genTubes', () {
    test('matches the JS board for every seed/config pair', () {
      final configs = fixture['genTubes'] as Map<String, dynamic>;
      for (final key in configs.keys) {
        final parts = key.split('_');
        final c = int.parse(parts[0]);
        final e = int.parse(parts[1]);
        final bySeed = configs[key] as Map<String, dynamic>;
        for (final seedStr in bySeed.keys) {
          final seed = int.parse(seedStr);
          final expected = _tubes(bySeed[seedStr]);
          final actual = genTubes(seed, c, e);
          expect(
            actual,
            equals(expected),
            reason: 'genTubes(seed=$seed, c=$c, e=$e)',
          );
        }
      }
    });
  });

  group('invMoves', () {
    test('matches the JS output on a fixed board', () {
      final board = [
        [0, 0, 0, 1],
        [1, 2, 2],
        <int>[],
        [2, 0],
      ];
      final expected = fixture['invMoves'] as List;
      final actual = invMoves(board);
      expect(actual.length, expected.length);
      for (var i = 0; i < expected.length; i++) {
        final e = expected[i] as List;
        expect(actual[i].d, e[0]);
        expect(actual[i].s, e[1]);
        expect(actual[i].k, e[2]);
      }
    });
  });

  group('Pour construction', () {
    test('tubes match the JS board for seeds 1..50', () {
      final bySeed = fixture['pour'] as Map<String, dynamic>;
      for (final seedStr in bySeed.keys) {
        final seed = int.parse(seedStr);
        final expected = _tubes(bySeed[seedStr]['tubes']);
        final p = Pour(seed, 9, 5);
        expect(p.tubes, equals(expected), reason: 'Pour(seed=$seed)');
      }
    });
  });

  group('Split construction', () {
    test('tubes match the JS board for seeds 1..50', () {
      final bySeed = fixture['split'] as Map<String, dynamic>;
      for (final seedStr in bySeed.keys) {
        final seed = int.parse(seedStr);
        final expected = _tubes(bySeed[seedStr]['tubes']);
        final s = Split(seed, 7, 3, 3);
        expect(s.tubes, equals(expected), reason: 'Split(seed=$seed)');
      }
    });
  });

  group('Fuse construction', () {
    test('grid matches the JS board for seeds 1..50', () {
      final bySeed = fixture['fuse'] as Map<String, dynamic>;
      for (final seedStr in bySeed.keys) {
        final seed = int.parse(seedStr);
        final expected = (bySeed[seedStr]['grid'] as List).cast<int>();
        final f = Fuse(seed);
        expect(f.grid, equals(expected), reason: 'Fuse(seed=$seed)');
      }
    });
  });

  group('Recipe construction', () {
    test('tubes and recipes match the JS output for seeds 1..50', () {
      final bySeed = fixture['recipe'] as Map<String, dynamic>;
      for (final seedStr in bySeed.keys) {
        final seed = int.parse(seedStr);
        final expectedTubes = _tubes(bySeed[seedStr]['tubes']);
        final expectedRecipes = _tubes(bySeed[seedStr]['recipes']);
        final r = Recipe(seed);
        expect(r.tubes, equals(expectedTubes), reason: 'Recipe(seed=$seed).tubes');
        expect(r.recipes, equals(expectedRecipes), reason: 'Recipe(seed=$seed).recipes');
      }
    });
  });

  group('best() AI playout parity', () {
    test('Pour: identical move sequence and outcome to JS, greedy (blunder=0)', () {
      final bySeed = fixture['playoutPour'] as Map<String, dynamic>;
      for (final seedStr in bySeed.keys) {
        final seed = int.parse(seedStr);
        final aiSeed = seed * 7 + 1;
        final expected = bySeed[seedStr] as Map<String, dynamic>;
        final expectedMoves = (expected['moves'] as List)
            .map((m) => ((m as List)[0] as int, m[1] as int))
            .toList();

        final g = Pour(seed, 9, 5);
        final rnd = mb32(aiSeed);
        final actualMoves = <(int, int)>[];
        var guard = 0;
        while (!g.over && guard < 400) {
          final m = best(g, 1, 0.0, rnd);
          if (m == null) break;
          g.act(m.$1, m.$2);
          actualMoves.add(m);
          guard++;
        }

        expect(actualMoves, equals(expectedMoves), reason: 'Pour(seed=$seed) move sequence');
        expect(g.scores, equals((expected['scores'] as List).cast<int>()));
        expect(g.leader, expected['leader']);
      }
    });

    test('Fuse: identical move sequence and outcome to JS, greedy (blunder=0)', () {
      final bySeed = fixture['playoutFuse'] as Map<String, dynamic>;
      for (final seedStr in bySeed.keys) {
        final seed = int.parse(seedStr);
        final aiSeed = seed * 7 + 1;
        final expected = bySeed[seedStr] as Map<String, dynamic>;
        final expectedMoves = (expected['moves'] as List)
            .map((m) => ((m as List)[0] as int, m[1] as int))
            .toList();

        final g = Fuse(seed);
        final rnd = mb32(aiSeed);
        final actualMoves = <(int, int)>[];
        var guard = 0;
        while (!g.over && guard < 400) {
          final m = best(g, 1, 0.0, rnd);
          if (m == null) break;
          g.act(m.$1, m.$2);
          actualMoves.add(m);
          guard++;
        }

        expect(actualMoves, equals(expectedMoves), reason: 'Fuse(seed=$seed) move sequence');
        expect(g.scores, equals((expected['scores'] as List).cast<int>()));
        expect(g.leader, expected['leader']);
      }
    });
  });
}
